### ISSUE TITLE
Only shows a white screen when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [rhysd/tweet-app#1]
Only shows a white screen when not connected to the internet:

![](https://github.com/AppImage/appimage.github.io/blob/487e84690a282c366c0058e41131cc5764d1a9f5/database/Tweet/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1311

**Comment by rhysd** [comment]
When are you seeing the window? After installing this app or while installation

**Comment by probonopd** [comment]
I am seeing when executing the AppImage on Ubuntu 14.04 without internet connectivity. (With AppImage, there is no need to install anything.)

**Comment by rhysd** [comment]
OK, thanks.

**Comment by rhysd** [comment]
![2019-02-27 16 06 21](https://user-images.githubusercontent.com/823277/53485048-9047b700-3ac8-11e9-80aa-ca5091461195.png)

I implemented a page to notify network is unavailable. The page will be automatically updated when network is back to available thanks to [online/offline events](https://developer.mozilla.org/ja/docs/Web/API/NavigatorOnLine/Online_and_offline_events).
