### ISSUE TITLE
Support for Flatpak, Snap and Appimage

### ISSUE THREAD

**Issue by dtantono** [rhysd/tweet-app#23]
Hi
it will be perfect to support distro-agnostic packaging method such as Flatpak, Snap and Appimage. Is it possible to support Flatpak, Snap and Appimage for Linux?

**Comment by rhysd** [comment]
From v0.4.0, `tweet-app-0.4.0.zip` was added to the release assets, which is distribution-agnostic package. Just downloading it and running the executable in unarchived directory should work.
